#!/bin/tcsh -f
# Copyright (c) 2023 Matheus Garcia.  All rights reserved.
# 
# Redistribution and use in source and binary forms, with or without
# modification, are permitted provided that the following conditions are met:
# 
# 1. Redistributions of source code must retain the above copyright notice,
#    this list of conditions and the following disclaimer. 
# 
# 2. Redistributions in binary form must reproduce the above copyright notice,
#    this list of conditions and the following disclaimer in the documentation
#    and/or other materials provided with the distribution. 
# 
# 3. Neither the name of the author nor the names of its contributors may be
#    used to endorse or promote products derived from this software without
#    specific prior written permission. 
# 
# THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
# "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
# LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS
# FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE
# COPYRIGHT OWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT,
# INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING,
# BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS
# OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED
# AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY,
# OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT
# OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH
# DAMAGE.

echo 'You should run this script in the directory containing the game.\
Press ENTER to continue; Ctrl + C to cancel.'
echo "$<" >& /dev/null

set dir = "`find . -mindepth 1 | grep -aie '\.tmd"\$"' -e '\.tim"\$"' -e '\.seq"\$"'`"
if !( $#dir ) then
  echo No files found.
  exit 1
endif

rm -f autogen

@ size = "`printf '%d' 0x80090000`"

while ( $#dir )
  echo "local dload $dir[1] `printf '%x' $size`" >> autogen
  @ size = ( `wc -c < "$dir[1]"` + $size + 1 )
  shift dir
end

echo -n 'Type in the path for the PS-X EXE file: '
echo "local load $<\
go" >> autogen

echo 'Script generated successfully!'
