#!/bin/tcsh -f

echo 'You should run this script in the directory containing the game.\
Press ENTER to continue; Ctrl + C to cancel.'
head -1 >& /dev/null

set dir = "`find . -mindepth 1 | grep -aie '\.tmd"\$"' -e '\.tim"\$"' -e '\.seq"\$"'`"
if !( $#dir ) then
  echo No files found.
  exit 1
endif

rm -f autogen

@ size = "`printf '%d' 0x80090000`"

while ( $#dir )
  echo "local dload $dir[1] `printf '%x' $size`" >> autogen
  @ size = ( `wc -c < "$dir[1]"` + $size + 1 )
  shift dir
end

echo -n 'Type in the path for the PS-X EXE file: '
echo "local load `head -1`\
go" >> autogen

echo 'Script generated successfully!'
